{{- if and (.Values.mongodb.enabled) (not .Values.microcks.dependencies.mongodb.auth.secretRef) }}
---
kind: Secret
apiVersion: v1
metadata:
  name: "{{ .Values.appName }}-mongodb-connection"
  labels:
    app: "{{ .Values.appName }}"
    container: mongodb
    group: microcks
    {{- include "microcks-common-labels" . | nindent 4 }}
  annotations:
    {{- include "microcks-secret-annotations" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: "{{ .Values.microcks.dependencies.mongodb.auth.username }}"
data:
  {{- if .Values.microcks.dependencies.mongodb.auth.password }}
  password: {{ .Values.microcks.dependencies.mongodb.auth.password | b64enc | quote }}
  {{- end }}
{{- end }}

{{- if and .Values.keycloak.enabled (not .Values.keycloak.secretRef) }}
---
kind: Secret
apiVersion: v1
metadata:
  name: "{{ .Values.appName }}-keycloak-admin"
  labels:
    app: "{{ .Values.appName }}"
    container: keycloak
    group: microcks
type: kubernetes.io/basic-auth
stringData:
  username: "{{ .Values.microcks.dependencies.keycloak.auth.adminUsername }}"
data:
  {{- if .Values.microcks.dependencies.keycloak.auth.adminPassword }}
  password: {{ .Values.keycloak.adminPassword | b64enc | quote }}
  {{- end }}
{{- end }}