{{- if .Values.microcks.service.app.enabled -}}
kind: Service
apiVersion: v1
metadata:
  name: "{{ .Values.appName }}"
  labels:
    app: "{{ .Values.appName }}"
    container: spring
    group: microcks
    {{- include "microcks-common-labels" . | nindent 4 }}
  annotations:
    {{- include "microcks-common-annotations" . | nindent 4 }}
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: spring
  type: {{ .Values.microcks.service.app.type | quote }}
  sessionAffinity: None
  selector:
    app: "{{ .Values.appName }}"
    container: spring
    group: microcks
{{- end }}
---
{{- if .Values.microcks.service.grpc.enabled -}}
kind: Service
apiVersion: v1
metadata:
  name: "{{ .Values.appName }}-grpc"
  labels:
    app: "{{ .Values.appName }}"
    container: spring
    group: microcks
    {{- include "microcks-common-labels" . | nindent 4 }}
  annotations:
    {{- include "microcks-common-annotations" . | nindent 4 }}
spec:
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: spring-grpc
  type: {{ .Values.microcks.service.grpc.type | quote }}
  sessionAffinity: None
  selector:
    app: "{{ .Values.appName }}"
    container: spring
    group: microcks
{{- end }}
{{- if and .Values.features.async.enabled .Values.features.async.service.enabled }}
---
kind: Service
apiVersion: v1
metadata:
  name: "{{ .Values.appName }}-async-minion"
  labels:
    app: "{{ .Values.appName }}"
    container: async-minion
    group: microcks
    {{- include "microcks-common-labels" . | nindent 4 }}
  annotations:
    {{- include "microcks-common-annotations" . | nindent 4 }}
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: async-minion
  type: {{ .Values.features.async.service.type | quote }}
  sessionAffinity: None
  selector:
    app: "{{ .Values.appName }}"
    container: async-minion
    group: microcks
{{- end }}
