{{- if and (.Values.mongodb.install) (not .Values.mongodb.secretRef) }}
---
kind: Secret
apiVersion: v1
metadata:
  name: "{{ .Values.appName }}-mongodb-connection"
  labels:
    app: "{{ .Values.appName }}"
    container: mongodb
    group: microcks
    {{- include "microcks-common-labels" . | nindent 4 }}
  annotations:
    {{- include "microcks-common-annotations" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: "{{ .Values.mongodb.username }}"
data:
  {{- if .Values.mongodb.password }}
  password: {{ .Values.mongodb.password | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  adminPassword: {{ randAlphaNum 40 | b64enc | quote }}
{{- end }}
