nameOverride: ""
# namespaceOverride: ""
imagePullSecrets: []
pod:
  labels: {}
  annotations: {}
  image:
    registry: "quay.io"
    repository: "microcks/microcks-postman-runtime"
    tag: "latest"
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    requests:
      memory: 60Mi
      cpu: 50m
    limits:
      memory: 120Mi
      cpu: 100m
  logLevel: info
service:
  labels: {}
  annotations: {}
  port: 8000
  targetPort: 3000