appName: microcks

microcks:
  url: microcks-microcks.192.168.99.100.nip.io
  # baseContext should always end with a trailing `/`, e.g. `/mock-server/microcks/`
  baseContext: /
  ingress:
    enabled: true
    secretRef: my-secret-for-microcks-ingress
    annotations:
      kubernetes.io/ingress.class: nginx
      # cert-manager.io/issuer: my-cert-issuer
      # kubernetes.io/tls-acme: "true"
  generateCert: true
  image: quay.io/microcks/microcks:1.2.0
  replicas: 1
  resources:
    #requests:
      #cpu: 250m
      #memory: 400Mi
    limits:
      #cpu: 500m
      memory: 512Mi

postman:
  image: quay.io/microcks/microcks-postman-runtime:latest
  replicas: 1

keycloak:
  install: true
  realm: microcks
  url: keycloak-microcks.192.168.99.100.nip.io
  # baseContext should always end with a trailing `/`, e.g. `/mock-server/auth/`
  baseContext: /auth/
  #privateUrl: http://microcks-keycloak.microcks.svc.cluster.local:8080/auth
  ingress:
    enabled: true
    secretRef: my-secret-for-keycloak-ingress
    annotations:
      kubernetes.io/ingress.class: nginx
      # cert-manager.io/issuer: my-cert-issuer
      # kubernetes.io/tls-acme: "true"
  generateCert: true
  image: jboss/keycloak:10.0.1
  adminUsername: admin
  # Unless you uncomment following line, admin password will be randomly generated.
  # Beware that in case of update, new value will be generated and
  #adminPassword: 123

  persistent: true
  volumeSize: 1Gi
  postgresImage: centos/postgresql-95-centos7:latest
  username: userP
  # Unless you uncomment following line, admin password will be randoMly generated.
  # Beware that in case of update, new value will be generated and
  #password: 123

  serviceAccount: microcks-serviceaccount
  serviceAccountCredentials: ab54d329-e435-41ae-a900-ec6b3fe15c54

mongodb:
  install: true
  #uri: mongodb:27017
  #database: sampledb
  image: centos/mongodb-34-centos7:latest
  persistent: true
  volumeSize: 2Gi
  
  username: userM
  # Unless you uncomment following line, admin password will be randomly generated.
  # Beware that in case of update, new value will be generated and overwrite existing one.
  #password: 123

  # Or you can uncomment secretRef block if username and password are provided through a Secret.
  #secretRef:
    #secret: mongodb
    #usernameKey: database-user
    #passwordKey: database-password

features:
  async:
    enabled: false
    defaultBinding: KAFKA
    defaultFrequency: 10
    defaultAvroEncoding: RAW
    
    image: quay.io/microcks/microcks-async-minion:1.2.0

    kafka:
      install: true
      url: 192.168.99.100.nip.io
      #url: kafka-bootstrap:9092
      persistent: false
      volumeSize: 2Gi
      resources:
        #requests:
          #cpu: 100m
          #memory: 256Mi
        limits:
          #cpu: 500m
          memory: 800Mi
      zkResources:
        #requests:
          #cpu: 100m
          #memory: 256Mi
        limits:
          #cpu: 500m
          memory: 800Mi
      schemaRegistry:
        #url: http://schema-registry.192.168.99.100.nip.io
        confluent: true
        username: microcks
        credentialsSource: USER_INFO

    # Uncomment the mqtt.url and put a valid endpoint address below to enable MQTT support.
    mqtt:
      #url: artemis:1883
      username: microcks
      password: microcks

  repositoryFilter:
    enabled: false
    labelKey: app
    labelLabel: Application
    labelList: app,status