{{- if and .Values.keycloak.enabled .Values.keycloak.ingress.enabled }}
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: "{{ .Values.appName }}-keycloak"
  labels:
    app: "{{ .Values.appName }}"
    group: microcks
    {{- include "microcks-common-labels" . | nindent 4 }}
  annotations:
    {{- include "microcks-common-annotations" . | nindent 4 }}
    {{- with .Values.keycloak.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.keycloak.ingress.ingressClassName }}
  ingressClassName: {{ .Values.keycloak.ingress.ingressClassName | quote }}
  {{- end }}
  {{- if .Values.keycloak.ingress.tls }}
  tls:
    {{- range .Values.keycloak.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      {{- with .secretName }}
      secretName: {{ . }}
      {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.keycloak.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if .pathType }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              service:
                name: "{{ $.Values.appName }}-keycloak"
                port:
                  number: 8080
            {{- end }}
      {{- end }}
{{- end }}
