{{- if (not .Values.keycloak.secretRef) }}
---
kind: Secret
apiVersion: v1
metadata:
  name: "{{ .Values.appName }}-keycloak-admin"
  labels:
    app: "{{ .Values.appName }}"
    container: keycloak
    group: microcks
type: kubernetes.io/basic-auth
stringData:
  username: "{{ .Values.keycloak.adminUsername }}"
  postgresUsername: "{{ .Values.keycloak.username }}"
data:
  {{- if .Values.keycloak.adminPassword }}
  password: {{ .Values.keycloak.adminPassword | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}
  {{- if .Values.keycloak.password }}
  postgresPassword: {{ .Values.keycloak.password | b64enc | quote }}
  {{- else }}
  postgresPassword: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}
